-- MySQL Script generated by MySQL Workbench
-- Tue Oct 10 22:56:42 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_cfp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_cfp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_cfp` DEFAULT CHARACTER SET utf8 ;
USE `db_cfp` ;

-- -----------------------------------------------------
-- Table `db_cfp`.`cfp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cfp`.`cfp` (
  `id_cfp` INT NOT NULL,
  `nome` VARCHAR(200) NULL,
  `morada` VARCHAR(200) NULL,
  `contacto` VARCHAR(9) NULL,
  `email` VARCHAR(200) NULL,
  PRIMARY KEY (`id_cfp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cfp`.`agrupamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cfp`.`agrupamento` (
  `id_agrupamento` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `id_cfp` INT NULL,
  `morada` VARCHAR(200) NULL,
  `contacto` VARCHAR(200) NULL,
  `email` VARCHAR(9) NULL,
  PRIMARY KEY (`id_agrupamento`),
  INDEX `id_cfp_idx` (`id_cfp` ASC),
  CONSTRAINT `id_cfp`
    FOREIGN KEY (`id_cfp`)
    REFERENCES `db_cfp`.`cfp` (`id_cfp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cfp`.`escola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cfp`.`escola` (
  `id_escola` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `id_agrupamento` INT NULL,
  `contacto` VARCHAR(9) NULL,
  `email` VARCHAR(200) NULL,
  `morada` VARCHAR(200) NULL,
  PRIMARY KEY (`id_escola`),
  INDEX `id_agrupamento` (`id_agrupamento` ASC),
  CONSTRAINT `id_agrupamento`
    FOREIGN KEY (`id_agrupamento`)
    REFERENCES `db_cfp`.`agrupamento` (`id_agrupamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cfp`.`habilitacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cfp`.`habilitacao` (
  `id_habilitacao` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  PRIMARY KEY (`id_habilitacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cfp`.`escalao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cfp`.`escalao` (
  `id_escalao` INT NOT NULL,
  `indice` INT NULL,
  PRIMARY KEY (`id_escalao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cfp`.`formando`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cfp`.`formando` (
  `id_formando` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NULL,
  `id_escola` INT NULL,
  `telemovel` VARCHAR(9) NULL,
  `id_habilitacao` INT NULL,
  `id_escalao` INT NULL,
  `morada` VARCHAR(100) NULL,
  `cod_postal` VARCHAR(45) NULL,
  `anos_servico` INT NULL,
  `e_mail` VARCHAR(100) NULL,
  `cc` VARCHAR(45) NULL,
  `contribuinte` VARCHAR(45) NULL,
  `horas` INT NULL,
  `genero` TINYINT(1) NULL,
  PRIMARY KEY (`id_formando`),
  INDEX `id_escola_idx` (`id_escola` ASC),
  INDEX `id_hablitacao_idx` (`id_habilitacao` ASC),
  INDEX `id_escalao_idx` (`id_escalao` ASC),
  CONSTRAINT `id_escola`
    FOREIGN KEY (`id_escola`)
    REFERENCES `db_cfp`.`escola` (`id_escola`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_hablitacao`
    FOREIGN KEY (`id_habilitacao`)
    REFERENCES `db_cfp`.`habilitacao` (`id_habilitacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_escalao`
    FOREIGN KEY (`id_escalao`)
    REFERENCES `db_cfp`.`escalao` (`id_escalao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cfp`.`area_formacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cfp`.`area_formacao` (
  `id_area_formacao` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(300) NULL,
  `codigo` VARCHAR(4) NULL,
  PRIMARY KEY (`id_area_formacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cfp`.`modalidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cfp`.`modalidade` (
  `id_modalidade` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  PRIMARY KEY (`id_modalidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cfp`.`acao_formacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cfp`.`acao_formacao` (
  `id_acao_formacao` INT NOT NULL AUTO_INCREMENT,
  `id_area_formacao` INT NULL,
  `id_modalidade` INT NULL,
  `data_acreditacao` DATE NULL,
  `data_proposta` DATE NULL,
  `codigo` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  `avaliacao` VARCHAR(300) NULL,
  `observacoes` VARCHAR(300) NULL,
  `creditos` DECIMAL NULL,
  `data_validade` DATE NULL,
  `subnome` VARCHAR(150) NULL,
  `reg_acreditacao` VARCHAR(45) NULL,
  `horas_pre` INT NULL,
  `horas_nao_pre` INT NULL,
  PRIMARY KEY (`id_acao_formacao`),
  INDEX `id_area_formacao_idx` (`id_area_formacao` ASC),
  INDEX `id_tipo_formacao_idx` (`id_modalidade` ASC),
  CONSTRAINT `id_area_formacao`
    FOREIGN KEY (`id_area_formacao`)
    REFERENCES `db_cfp`.`area_formacao` (`id_area_formacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_tipo_formacao`
    FOREIGN KEY (`id_modalidade`)
    REFERENCES `db_cfp`.`modalidade` (`id_modalidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cfp`.`edicao_formacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cfp`.`edicao_formacao` (
  `id_edicao_formacao` INT NOT NULL,
  `id_acao_formacao` INT NULL,
  `data_inicio` DATE NULL,
  `data_fim` DATE NULL,
  PRIMARY KEY (`id_edicao_formacao`),
  INDEX `id_acao_formacao_idx` (`id_acao_formacao` ASC),
  CONSTRAINT `id_acao_formacao`
    FOREIGN KEY (`id_acao_formacao`)
    REFERENCES `db_cfp`.`acao_formacao` (`id_acao_formacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cfp`.`edicao_formador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cfp`.`edicao_formador` (
  `id_edicao_formador` INT NOT NULL AUTO_INCREMENT,
  `id_formador` INT NULL,
  `id_edicao` INT NULL,
  PRIMARY KEY (`id_edicao_formador`),
  INDEX `id_edicao_idx` (`id_edicao` ASC),
  INDEX `id_formador_idx` (`id_formador` ASC),
  CONSTRAINT `id_edicao`
    FOREIGN KEY (`id_edicao`)
    REFERENCES `db_cfp`.`edicao_formacao` (`id_edicao_formacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_formador`
    FOREIGN KEY (`id_formador`)
    REFERENCES `db_cfp`.`formando` (`id_formando`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cfp`.`formador_acao_formacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cfp`.`formador_acao_formacao` (
  `id_formador_acao_formacao` INT NOT NULL,
  `id_formador_acao` INT NOT NULL,
  `id_acao_formacao` INT NULL,
  PRIMARY KEY (`id_formador_acao_formacao`, `id_formador_acao`),
  INDEX `id_acao_formador_idx` (`id_acao_formacao` ASC),
  INDEX `id_formador_idx` (`id_formador_acao` ASC),
  CONSTRAINT `id_acao_formador`
    FOREIGN KEY (`id_acao_formacao`)
    REFERENCES `db_cfp`.`acao_formacao` (`id_acao_formacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_formador_acao`
    FOREIGN KEY (`id_formador_acao`)
    REFERENCES `db_cfp`.`formando` (`id_formando`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cfp`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cfp`.`turma` (
  `id_turma` INT NOT NULL,
  `id_formando_turma` INT NOT NULL,
  `id_acao_edicao` INT NULL,
  `nota` DECIMAL NULL,
  PRIMARY KEY (`id_turma`, `id_formando_turma`),
  INDEX `id_formando_turma_idx` (`id_formando_turma` ASC),
  INDEX `id_edicao_idx` (`id_acao_edicao` ASC),
  CONSTRAINT `id_formando_turma`
    FOREIGN KEY (`id_formando_turma`)
    REFERENCES `db_cfp`.`formando` (`id_formando`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_acao_edicao`
    FOREIGN KEY (`id_acao_edicao`)
    REFERENCES `db_cfp`.`edicao_formacao` (`id_edicao_formacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cfp`.`dominio_formacacao_formador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cfp`.`dominio_formacacao_formador` (
  `id_d_f_f` INT NOT NULL,
  `id_dominio_formacao` INT NOT NULL,
  `id_formador_dom` INT NOT NULL,
  PRIMARY KEY (`id_d_f_f`, `id_dominio_formacao`, `id_formador_dom`),
  INDEX `id_formador_idx` (`id_formador_dom` ASC),
  INDEX `id_dominio_formacao_idx` (`id_dominio_formacao` ASC),
  CONSTRAINT `id_formador_dominio_formacao`
    FOREIGN KEY (`id_formador_dom`)
    REFERENCES `db_cfp`.`formando` (`id_formando`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_dominio_formacao`
    FOREIGN KEY (`id_dominio_formacao`)
    REFERENCES `db_cfp`.`area_formacao` (`id_area_formacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cfp`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cfp`.`login` (
  `id_login` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  PRIMARY KEY (`id_login`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cfp`.`artigo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cfp`.`artigo` (
  `id_artigo` INT NOT NULL,
  PRIMARY KEY (`id_artigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cfp`.`grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cfp`.`grupos` (
  `id_grupos` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NULL,
  `nome` VARCHAR(300) NULL,
  PRIMARY KEY (`id_grupos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cfp`.`releva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cfp`.`releva` (
  `id_releva` INT NOT NULL,
  `id_acao_formacao_releva` INT NOT NULL,
  `id_artigo_releva` INT NOT NULL,
  `id_grupos_releva` INT NOT NULL,
  PRIMARY KEY (`id_releva`, `id_artigo_releva`, `id_acao_formacao_releva`, `id_grupos_releva`),
  INDEX `id_acao_formacao_idx` (`id_acao_formacao_releva` ASC),
  INDEX `id_artigo5_idx` (`id_artigo_releva` ASC),
  INDEX `id_areas_idx` (`id_grupos_releva` ASC),
  CONSTRAINT `id_acao_formacao_releva`
    FOREIGN KEY (`id_acao_formacao_releva`)
    REFERENCES `db_cfp`.`acao_formacao` (`id_acao_formacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_artigo_releva`
    FOREIGN KEY (`id_artigo_releva`)
    REFERENCES `db_cfp`.`artigo` (`id_artigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_grupos_releva`
    FOREIGN KEY (`id_grupos_releva`)
    REFERENCES `db_cfp`.`grupos` (`id_grupos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cfp`.`formando_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cfp`.`formando_grupo` (
  `id_formando_grupo` INT NOT NULL,
  `id_formando_g` INT NOT NULL,
  `id_grupo` INT NULL,
  PRIMARY KEY (`id_formando_grupo`, `id_formando_g`),
  INDEX `id_formando_idx` (`id_formando_g` ASC),
  INDEX `id_grupo_idx` (`id_grupo` ASC),
  CONSTRAINT `id_formando`
    FOREIGN KEY (`id_formando_g`)
    REFERENCES `db_cfp`.`formando` (`id_formando`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_grupo`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `db_cfp`.`grupos` (`id_grupos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
